name1 = str(input("First name "))
day1 = int(input("First day "))
month1 = int(input("First month "))
year1 = int(input("First year "))
name2 = str(input("Second name "))
day2 = int(input("Second day "))
month2 = int(input("Second month "))
year2 = int(input("Second year "))
name3 = str(input("Third name "))
day3 = int(input("Third day "))
month3 = int(input("Third month "))
year3 = int(input("Third year "))
name4 = str(input("Fourth name "))
day4 = int(input("Fourth day "))
month4 = int(input("Fourth month "))
year4 = int(input("Fourth year "))

print("Names".ljust(20),"Birthdays".ljust(10))
print(name1.ljust(20),month1,"/",day1,"/",year1)
print(name2.ljust(20),month2,"/",day2,"/",year2)
print(name3.ljust(20),month3,"/",day3,"/",year3)
print(name4.ljust(20),month4,"/",day4,"/",year4)
